<?php


function mymodule_theme($existing, $type, $theme, $path) {
    return [
        'node__framework__full' => [
          'base hook' => 'node',
          'template'  => 'node--framework--full',
        ],
        'node__view__frameworks' => [
          'template'  => 'node--view--frameworks',
        ],
        'node__view__frontpage__page_1' => [
          'template'  => 'node--view--frontpage--page-1',
        ],
      ];

}
/**
 * Implements hook_preprocess_node().
 */
function mymodule_preprocess_node(&$variables) {

 // dump($variables);die;
  
    $node = $variables['node'];
    if ($node->getType() == 'framework') {
       $termId = $node->get('field_type')->target_id;
       $variables["id_tax"]=$termId;
        $variables["name"]=$variables["content"]["field_name"][0]["#context"]["value"];
        $variables["type"]=$variables["content"]["field_type"][0]["#title"];
        $variables["resume"]=$variables["content"]["field_resume"][0]["#context"]["value"];
        $variables["logo"]=$variables["content"]["field_logo"][0]["#item"];
        $variables["video"]=$variables["content"]["field_video"];
        $variables["file"]=$variables["content"]["field_file"];


      }
 
  }




?>